### ISSUE TITLE
Using PopPunk for plasmids

### ISSUE THREAD

**Issue by andreaniml** [bacpop/PopPUNK#200]
Hello!

I'm wondering if PopPUNK could be aplied to a group of plasmids sequences (some are complete, others are predicted by other software). I believe the program would work, but I don't know if I wouldn't be breaking some statistical assumptions it uses.
Can I use popPUNK for clustering plasmids? 
Cheers!

Maria Luiza

**Comment by nickjcroucher** [comment]
It's fine in principle, but it will only work when there are at least some shared k-mers between the plasmids - if you use a closely-related set of elements, with a short k-mer size range, then it should work - let us know!
