### ISSUE TITLE
Error install Poppunk

### ISSUE THREAD

**Issue by OrsonMM** [bacpop/PopPUNK#211]
I have:  These error 

$ python3 poppunk-runner.py

Traceback (most recent call last):
  File "poppunk-runner.py", line 7, in <module>
    from PopPUNK.__main__ import main
  File "/home/administrador/programas/PopPUNK/PopPUNK/__main__.py", line 16, in <module>
    import poppunk_refine
ModuleNotFoundError: No module named 'poppunk_refine'

**Comment by nickjcroucher** [comment]
@OrsonMM please use the issue template and tell us how you installed PopPUNK.

**Versions**


**Command used and output returned**


**Describe the bug**

**Comment by aspitaleri** [comment]
Hi - got identical error and I fixed as follow:
After cloning the git, running python3 poppunk-runner.py it does not work (no module named "poppunk_refine". You need to build/install first using setup.py. I have install all dependencies, including cython and pybind11. In my Ubuntu I needed to export the path:
export pybind11_DIR=/usr/local/lib/python3.8/dist-packages/pybind11/share/cmake/pybind11/

Finally, run 

python setup.py build
sudo python setup.py install

Then python poppunk-runner.py or just type poppunk works fine!

**Comment by johnlees** [comment]
Thanks @aspitaleri 

This would work, or you can also install via conda. pip installation is temporarily unsupported.
