### ISSUE TITLE
poppunk_visualise failed

### ISSUE THREAD

**Issue by shaodongyan** [bacpop/PopPUNK#219]
**Versions**
poppunk 2.5.0

**Command used and output returned**
Firstly, I used "poppunk_assign --db /public/home/s20203050772/database/popunk/e_coli_poppunk  --query qfile.tsv \
--output poppunk_clusters_new --threads 56 --update-db"
Secondly,I used " poppunk_visualise --ref-db poppunk_clusters_new/  --tree both --microreact --output dense_mst_viz".

**Describe the bug**
But , I did it with Graph-tools OpenMP parallelisation enabled: with 1 threads
PopPUNK: visualise
Loading previously refined model
Completed model loading
Generating MST from dense distances (may be slow)
Starting calculation of minimum-spanning tree
Completed calculation of minimum-spanning tree
Drawing MST
Building phylogeny
Writing microreact output
Parsed data, now writing to CSV
Running mandrake
Running on CPU
Preprocessing 10800 samples with perplexity = 20 took 44122ms
Optimizing       Progress: 99.9%, eta=0.0010, Eq=0.9650969196, clashes=0.0%
Optimizing done in 0s
Traceback (most recent call last):
  File "/public/home/s20203050772/miniconda3/envs/poppunk/bin/poppunk_visualise", line 11, in <module>
    sys.exit(main())
  File "/public/home/s20203050772/miniconda3/envs/poppunk/lib/python3.10/site-packages/PopPUNK/visualise.py", line 624, in main
    generate_visualisations(args.query_db,
  File "/public/home/s20203050772/miniconda3/envs/poppunk/lib/python3.10/site-packages/PopPUNK/visualise.py", line 561, in generate_visualisations
    url = createMicroreact(output, microreact_files, api_key)
  File "/public/home/s20203050772/miniconda3/envs/poppunk/lib/python3.10/site-packages/PopPUNK/plot.py", line 779, in createMicroreact
    with pkg_resources.resource_stream(__name__, 'data/microreact_example.pkl') as example_pickle:
  File "/public/home/s20203050772/miniconda3/envs/poppunk/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1160, in resource_stream
    return get_provider(package_or_requirement).get_resource_stream(
  File "/public/home/s20203050772/miniconda3/envs/poppunk/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1632, in get_resource_stream
    return open(self._fn(self.module_path, resource_name), 'rb')
FileNotFoundError: [Errno 2] 没有那个文件或目录: '/public/home/s20203050772/miniconda3/envs/poppunk/lib/python3.10/site-packages/PopPUNK/data/microreact_example.pkl'
Please Help me,Thanks!

**Comment by nickjcroucher** [comment]
If you download this file with `curl -o /public/home/s20203050772/miniconda3/envs/poppunk/lib/python3.10/site-packages/PopPUNK/data/microreact_example.pkl https://github.com/bacpop/PopPUNK/blob/master/PopPUNK/data/microreact_example.pkl`, does that resolve thew issue?

**Comment by shaodongyan** [comment]
> If you download this file with `curl -o /public/home/s20203050772/miniconda3/envs/poppunk/lib/python3.10/site-packages/PopPUNK/data/microreact_example.pkl https://github.com/bacpop/PopPUNK/blob/master/PopPUNK/data/microreact_example.pkl`, does that resolve thew issue?

Thanks！ That  resolve thew issue！

**Comment by shaodongyan** [comment]
Sorry, But I need more help , I fit a model with K=7, but I visualise this model ,it has cluster more than 7, How can i solve it ?thanks!

**Comment by shaodongyan** [comment]
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/66828533/190901643-227e52a1-07f6-4567-b7fd-a4886f51b1ce.png">
![ourdatabase_dbscan](https://user-images.githubusercontent.com/66828533/190901676-c1ba12c0-8b80-4bde-afe9-6c19941fb757.png)
Two things can't match

**Comment by shaodongyan** [comment]
![ourdatabase_dbscan](https://user-images.githubusercontent.com/66828533/190901750-eb96f86a-8cff-45a4-9a46-26aaee29645e.png)

**Comment by shaodongyan** [comment]
I launch a new issue . Close it
