### ISSUE TITLE
Fit a dbscan model with 7 Clusters But visualise's result has more than 7 Clusters

### ISSUE THREAD

**Issue by shaodongyan** [bacpop/PopPUNK#220]
**Versions**
PopPUNK 2.5.0
**Command used and output returned**

poppunk --fit-model dbscan --ref-db ourdatabase  --threads 56   --min-cluster-prop 0.0005
poppunk_visualise --ref-db ourdatabase --output example_viz --microreact
 

**Describe the bug**

with "poppunk --fit-model dbscan --ref-db ourdatabase  --threads 56   --min-cluster-prop 0.0005" We have a good result. 
![ourdatabase_dbscan](https://user-images.githubusercontent.com/66828533/190936878-edb97257-acd2-43ce-bb0e-f3e3a69245b6.png)

But after "poppunk_visualise --ref-db ourdatabase --output example_viz --microreact", It has the cluster numbers  that is same with number of  my isolates.
![image](https://user-images.githubusercontent.com/66828533/190937060-c57da290-e34e-4bab-87b6-456a26dc26b5.png)

Thanks, I need your help. I want to know how can we devide our isolates into 7 clusters

**Comment by nickjcroucher** [comment]
The "7" refers to the number of clusters identified in the distribution of pairwise distances, not the number of clusters in the population. Your dataset looks very diverse, which is why no isolates are clustered together. You might want to try lineage mode clustering instead (`--fit-model lineage`).

**Comment by johnlees** [comment]
The DBSCAN model isn't very good, it's identified a tiny cluster (in purple) at the origin.
You probably want to run network refinement on your model as you want a boundary between the DBSCAN clusters.
See https://poppunk.readthedocs.io/en/latest/model_fitting.html#refine

> I want to know how can we devide our isolates into 7 clusters

PopPUNK does not allow you to specify the number of clusters to divide the dataset into. You'd probably want to try hierarchical clustering or similar for that.
