### ISSUE TITLE
conda install fails

### ISSUE THREAD

**Issue by chahatupreti** [bacpop/PopPUNK#223]
I am trying to install poppunk using conda. However, it fails every time I do it and I have tried it on two different computers. 

Command used - 
```
conda create -n poppunk
conda activate poppunk
conda install -c bioconda poppunk
```

Output - 
![image](https://user-images.githubusercontent.com/9638057/191376411-94d8d4a8-232d-4c1c-955f-0daa1194b587.png)

And it keeps getting stuck at `Solving Environment`. I have also tried simply `conda install poppunk` but that too gave the same result.

Please let me know what I may be doing wrong. I have tried this on a Mac and Ubuntu.

Thanks!

**Comment by johnlees** [comment]
This may be due to the channel order, see the guide here: https://poppunk.readthedocs.io/en/latest/installation.html#installing-with-conda-recommended

so try running:
```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda install poppunk
```

**Comment by chahatupreti** [comment]
That worked! I thought I had tried that but evidently not. Thank you so much!
