### ISSUE TITLE
Problem installing latest version in conda - libglib

### ISSUE THREAD

**Issue by hmedwards** [bacpop/PopPUNK#228]
Hi, 
I can't install the latest version of poppunk due, it seems, to an issue with libglib? I'm not sure how to fix this. Any help appreciated! Thanks.

`$ conda config --add channels defaults
Warning: 'defaults' already in 'channels' list, moving to the top
$ conda config --add channels bioconda
Warning: 'bioconda' already in 'channels' list, moving to the top
$ conda config --add channels conda-forge
Warning: 'conda-forge' already in 'channels' list, moving to the top
$ conda create -n pp_env poppunk==2.5.0
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: home/anaconda3/envs/pp_env

  added / updated specs:
    - poppunk==2.5.0

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge None
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-2_gnu None
  aom                conda-forge/linux-64::aom-3.4.0-h27087fc_1 None
  at-spi2-atk        conda-forge/linux-64::at-spi2-atk-2.38.0-h0630a04_3 None
  at-spi2-core       conda-forge/linux-64::at-spi2-core-2.40.3-h0630a04_0 None
  atk-1.0            conda-forge/linux-64::atk-1.0-2.36.0-h3371d22_4 None
  biopython          conda-forge/linux-64::biopython-1.79-py310h5764c6d_2 None
  boost              conda-forge/linux-64::boost-1.74.0-py310h7c3ba0c_5 None
  boost-cpp          conda-forge/linux-64::boost-cpp-1.74.0-h75c5d50_8 None
  brotli             conda-forge/linux-64::brotli-1.0.9-h166bdaf_7 None
  brotli-bin         conda-forge/linux-64::brotli-bin-1.0.9-h166bdaf_7 None
  brotlipy           conda-forge/linux-64::brotlipy-0.7.0-py310h5764c6d_1004 None
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h7f98852_4 None
  c-ares             conda-forge/linux-64::c-ares-1.18.1-h7f98852_0 None
  ca-certificates    conda-forge/linux-64::ca-certificates-2022.9.24-ha878542_0 None
  cached-property    conda-forge/noarch::cached-property-1.5.2-hd8ed1ab_1 None
  cached_property    conda-forge/noarch::cached_property-1.5.2-pyha770c72_1 None
  cairo              conda-forge/linux-64::cairo-1.16.0-ha61ee94_1014 None
  cairomm            conda-forge/linux-64::cairomm-1.14.4-ha770c72_0 None
  cairomm-1.0        conda-forge/linux-64::cairomm-1.0-1.14.4-h09cb3b9_0 None
  certifi            conda-forge/noarch::certifi-2022.9.24-pyhd8ed1ab_0 None
  cffi               conda-forge/linux-64::cffi-1.15.1-py310h255011f_0 None
  charset-normalizer conda-forge/noarch::charset-normalizer-2.1.1-pyhd8ed1ab_0 None
  colorama           conda-forge/noarch::colorama-0.4.5-pyhd8ed1ab_0 None
  contourpy          conda-forge/linux-64::contourpy-1.0.5-py310hbf28c38_0 None
  cryptography       conda-forge/linux-64::cryptography-38.0.1-py310h597c629_0 None
  cycler             conda-forge/noarch::cycler-0.11.0-pyhd8ed1ab_0 None
  dbus               conda-forge/linux-64::dbus-1.13.6-h5008d03_3 None
  dendropy           bioconda/noarch::dendropy-4.5.2-pyh3252c3a_0 None
  docopt             conda-forge/noarch::docopt-0.6.2-py_1 None
  epoxy              conda-forge/linux-64::epoxy-1.5.10-h166bdaf_1 None
  expat              conda-forge/linux-64::expat-2.4.9-h27087fc_0 None
  ffmpeg             conda-forge/linux-64::ffmpeg-5.1.1-gpl_hfe78399_101 None
  font-ttf-dejavu-s~ conda-forge/noarch::font-ttf-dejavu-sans-mono-2.37-hab24e00_0 None
  font-ttf-inconsol~ conda-forge/noarch::font-ttf-inconsolata-3.000-h77eed37_0 None
  font-ttf-source-c~ conda-forge/noarch::font-ttf-source-code-pro-2.038-h77eed37_0 None
  font-ttf-ubuntu    conda-forge/noarch::font-ttf-ubuntu-0.83-hab24e00_0 None
  fontconfig         conda-forge/linux-64::fontconfig-2.14.0-hc2a2eb6_1 None
  fonts-conda-ecosy~ conda-forge/noarch::fonts-conda-ecosystem-1-0 None
  fonts-conda-forge  conda-forge/noarch::fonts-conda-forge-1-0 None
  fonttools          conda-forge/linux-64::fonttools-4.37.4-py310h5764c6d_0 None
  freetype           conda-forge/linux-64::freetype-2.12.1-hca18f0e_0 None
  fribidi            conda-forge/linux-64::fribidi-1.0.10-h36c2ea0_0 None
  gdk-pixbuf         conda-forge/linux-64::gdk-pixbuf-2.42.8-hff1cb4f_1 None
  gettext            conda-forge/linux-64::gettext-0.19.8.1-h27087fc_1009 None
  glib-tools         conda-forge/linux-64::glib-tools-2.74.0-h6239696_0 None
  gmp                conda-forge/linux-64::gmp-6.2.1-h58526e2_0 None
  gnutls             conda-forge/linux-64::gnutls-3.7.8-hf3e180e_0 None
  graph-tool         conda-forge/linux-64::graph-tool-2.45-py310haee70ea_2 None
  graph-tool-base    conda-forge/linux-64::graph-tool-base-2.45-py310hd8094d8_2 None
  graphite2          conda-forge/linux-64::graphite2-1.3.13-h58526e2_1001 None
  gtk3               conda-forge/linux-64::gtk3-3.24.34-h4d20fae_1 None
  h5py               conda-forge/linux-64::h5py-3.7.0-nompi_py310h416281c_101 None
  harfbuzz           conda-forge/linux-64::harfbuzz-5.2.0-hf9f4e7c_0 None
  hdbscan            conda-forge/linux-64::hdbscan-0.8.28-py310h96516ba_1 None
  hdf5               conda-forge/linux-64::hdf5-1.12.2-nompi_h2386368_100 None
  hicolor-icon-theme conda-forge/linux-64::hicolor-icon-theme-0.17-ha770c72_2 None
  icu                conda-forge/linux-64::icu-70.1-h27087fc_0 None
  idna               conda-forge/noarch::idna-3.4-pyhd8ed1ab_0 None
  joblib             conda-forge/noarch::joblib-1.2.0-pyhd8ed1ab_0 None
  jpeg               conda-forge/linux-64::jpeg-9e-h166bdaf_2 None
  keyutils           conda-forge/linux-64::keyutils-1.6.1-h166bdaf_0 None
  kiwisolver         conda-forge/linux-64::kiwisolver-1.4.4-py310hbf28c38_0 None
  krb5               conda-forge/linux-64::krb5-1.19.3-h3790be6_0 None
  lame               conda-forge/linux-64::lame-3.100-h166bdaf_1002 None
  lcms2              conda-forge/linux-64::lcms2-2.12-hddcbb42_0 None
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.36.1-hea4e1c9_2 None
  lerc               conda-forge/linux-64::lerc-4.0.0-h27087fc_0 None
  libblas            conda-forge/linux-64::libblas-3.9.0-16_linux64_openblas None
  libbrotlicommon    conda-forge/linux-64::libbrotlicommon-1.0.9-h166bdaf_7 None
  libbrotlidec       conda-forge/linux-64::libbrotlidec-1.0.9-h166bdaf_7 None
  libbrotlienc       conda-forge/linux-64::libbrotlienc-1.0.9-h166bdaf_7 None
  libcblas           conda-forge/linux-64::libcblas-3.9.0-16_linux64_openblas None
  libcups            conda-forge/linux-64::libcups-2.3.3-h3e49a29_2 None
  libcurl            conda-forge/linux-64::libcurl-7.85.0-h7bff187_0 None
  libdeflate         conda-forge/linux-64::libdeflate-1.14-h166bdaf_0 None
  libdrm             conda-forge/linux-64::libdrm-2.4.113-h166bdaf_0 None
  libedit            conda-forge/linux-64::libedit-3.1.20191231-he28a2e2_2 None
  libev              conda-forge/linux-64::libev-4.33-h516909a_1 None
  libffi             conda-forge/linux-64::libffi-3.4.2-h7f98852_5 None
  libgcc-ng          conda-forge/linux-64::libgcc-ng-12.1.0-h8d9b700_16 None
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-12.1.0-h69a702a_16 None
  libgfortran5       conda-forge/linux-64::libgfortran5-12.1.0-hdcd56e2_16 None
  libgirepository    conda-forge/linux-64::libgirepository-1.74.0-ha2a38d2_0 None
  libglib            conda-forge/linux-64::libglib-2.74.0-h7a41b64_0 None
  libgomp            conda-forge/linux-64::libgomp-12.1.0-h8d9b700_16 None
  libiconv           conda-forge/linux-64::libiconv-1.17-h166bdaf_0 None
  libidn2            conda-forge/linux-64::libidn2-2.3.3-h166bdaf_0 None
  liblapack          conda-forge/linux-64::liblapack-3.9.0-16_linux64_openblas None
  libnghttp2         conda-forge/linux-64::libnghttp2-1.47.0-hdcd2b5c_1 None
  libnsl             conda-forge/linux-64::libnsl-2.0.0-h7f98852_0 None
  libopenblas        conda-forge/linux-64::libopenblas-0.3.21-pthreads_h78a6416_3 None
  libpciaccess       conda-forge/linux-64::libpciaccess-0.16-h516909a_0 None
  libpng             conda-forge/linux-64::libpng-1.6.38-h753d276_0 None
  librsvg            conda-forge/linux-64::librsvg-2.54.4-h7abd40a_0 None
  libsqlite          conda-forge/linux-64::libsqlite-3.39.4-h753d276_0 None
  libssh2            conda-forge/linux-64::libssh2-1.10.0-haa6b8db_3 None
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-12.1.0-ha89aaad_16 None
  libtasn1           conda-forge/linux-64::libtasn1-4.19.0-h166bdaf_0 None
  libtiff            conda-forge/linux-64::libtiff-4.4.0-h55922b4_4 None
  libunistring       conda-forge/linux-64::libunistring-0.9.10-h7f98852_0 None
  libuuid            conda-forge/linux-64::libuuid-2.32.1-h7f98852_1000 None
  libva              conda-forge/linux-64::libva-2.16.0-h166bdaf_0 None
  libvpx             conda-forge/linux-64::libvpx-1.11.0-h9c3ff4c_3 None
  libwebp-base       conda-forge/linux-64::libwebp-base-1.2.4-h166bdaf_0 None
  libxcb             conda-forge/linux-64::libxcb-1.13-h7f98852_1004 None
  libxml2            conda-forge/linux-64::libxml2-2.10.2-h4c7fe37_1 None
  libzlib            conda-forge/linux-64::libzlib-1.2.12-h166bdaf_4 None
  mandrake           conda-forge/linux-64::mandrake-1.2.2-py310h7dbff7e_1 None
  matplotlib-base    conda-forge/linux-64::matplotlib-base-3.6.0-py310h8d5ebf3_0 None
  munkres            conda-forge/noarch::munkres-1.1.4-pyh9f0ad1d_0 None
  ncurses            conda-forge/linux-64::ncurses-6.3-h27087fc_1 None
  nettle             conda-forge/linux-64::nettle-3.8.1-hc379101_1 None
  networkx           conda-forge/noarch::networkx-2.8.7-pyhd8ed1ab_0 None
  numpy              conda-forge/linux-64::numpy-1.23.3-py310h53a5b5f_0 None
  openblas           conda-forge/linux-64::openblas-0.3.21-pthreads_h320a7e8_3 None
  openh264           conda-forge/linux-64::openh264-2.3.0-h27087fc_0 None
  openjpeg           conda-forge/linux-64::openjpeg-2.5.0-h7d73246_1 None
  openssl            conda-forge/linux-64::openssl-1.1.1q-h166bdaf_0 None
  p11-kit            conda-forge/linux-64::p11-kit-0.24.1-hc5aa10d_0 None
  packaging          conda-forge/noarch::packaging-21.3-pyhd8ed1ab_0 None
  pandas             conda-forge/linux-64::pandas-1.5.0-py310h769672d_0 None
  pango              conda-forge/linux-64::pango-1.50.11-h382ae3d_0 None
  pcre2              conda-forge/linux-64::pcre2-10.37-hc3806b6_1 None
  pillow             conda-forge/linux-64::pillow-9.2.0-py310hbd86126_2 None
  pip                conda-forge/noarch::pip-22.2.2-pyhd8ed1ab_0 None
  pixman             conda-forge/linux-64::pixman-0.40.0-h36c2ea0_0 None
  plotly             conda-forge/noarch::plotly-5.10.0-pyhd8ed1ab_0 None
  poppunk            bioconda/linux-64::poppunk-2.5.0-py310h2579afa_0 None
  pp-sketchlib       conda-forge/linux-64::pp-sketchlib-2.0.0-py310h5a37817_2 None
  pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-h36c2ea0_1001 None
  pycairo            conda-forge/linux-64::pycairo-1.21.0-py310h96fc21a_1 None
  pycparser          conda-forge/noarch::pycparser-2.21-pyhd8ed1ab_0 None
  pygobject          conda-forge/linux-64::pygobject-3.42.2-py310h964465f_0 None
  pyopenssl          conda-forge/noarch::pyopenssl-22.0.0-pyhd8ed1ab_1 None
  pyparsing          conda-forge/noarch::pyparsing-3.0.9-pyhd8ed1ab_0 None
  pysocks            conda-forge/noarch::pysocks-1.7.1-pyha2e5f31_6 None
  python             conda-forge/linux-64::python-3.10.6-h582c2e5_0_cpython None
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.2-pyhd8ed1ab_0 None
  python_abi         conda-forge/linux-64::python_abi-3.10-2_cp310 None
  pytz               conda-forge/noarch::pytz-2022.4-pyhd8ed1ab_0 None
  rapidnj            bioconda/linux-64::rapidnj-2.3.2-h9f5acd7_2 None
  readline           conda-forge/linux-64::readline-8.1.2-h0f457ee_0 None
  requests           conda-forge/noarch::requests-2.28.1-pyhd8ed1ab_1 None
  scikit-learn       conda-forge/linux-64::scikit-learn-1.1.2-py310h0c3af53_0 None
  scipy              conda-forge/linux-64::scipy-1.9.1-py310hdfbd76f_0 None
  setuptools         conda-forge/noarch::setuptools-65.4.1-pyhd8ed1ab_0 None
  sigcpp-2.0         conda-forge/linux-64::sigcpp-2.0-2.10.8-h27087fc_0 None
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0 None
  sparsehash         conda-forge/linux-64::sparsehash-2.0.4-h9c3ff4c_0 None
  svt-av1            conda-forge/linux-64::svt-av1-1.2.1-h27087fc_0 None
  tenacity           conda-forge/noarch::tenacity-8.1.0-pyhd8ed1ab_0 None
  threadpoolctl      conda-forge/noarch::threadpoolctl-3.1.0-pyh8a188c0_0 None
  tk                 conda-forge/linux-64::tk-8.6.12-h27826a3_0 None
  tqdm               conda-forge/noarch::tqdm-4.64.1-pyhd8ed1ab_0 None
  treeswift          bioconda/noarch::treeswift-1.1.28-pyh5e36f6f_0 None
  tzdata             conda-forge/noarch::tzdata-2022d-h191b570_0 None
  unicodedata2       conda-forge/linux-64::unicodedata2-14.0.0-py310h5764c6d_1 None
  urllib3            conda-forge/noarch::urllib3-1.26.11-pyhd8ed1ab_0 None
  wheel              conda-forge/noarch::wheel-0.37.1-pyhd8ed1ab_0 None
  x264               conda-forge/linux-64::x264-1!164.3095-h166bdaf_2 None
  x265               conda-forge/linux-64::x265-3.5-h924138e_3 None
  xorg-compositepro~ conda-forge/linux-64::xorg-compositeproto-0.4.2-h7f98852_1001 None
  xorg-damageproto   conda-forge/linux-64::xorg-damageproto-1.2.1-h7f98852_1002 None
  xorg-fixesproto    conda-forge/linux-64::xorg-fixesproto-5.0-h7f98852_1002 None
  xorg-inputproto    conda-forge/linux-64::xorg-inputproto-2.3.2-h7f98852_1002 None
  xorg-kbproto       conda-forge/linux-64::xorg-kbproto-1.0.7-h7f98852_1002 None
  xorg-libice        conda-forge/linux-64::xorg-libice-1.0.10-h7f98852_0 None
  xorg-libsm         conda-forge/linux-64::xorg-libsm-1.2.3-hd9c2040_1000 None
  xorg-libx11        conda-forge/linux-64::xorg-libx11-1.6.12-h36c2ea0_0 None
  xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.9-h7f98852_0 None
  xorg-libxaw        conda-forge/linux-64::xorg-libxaw-1.0.14-h7f98852_0 None
  xorg-libxcomposite conda-forge/linux-64::xorg-libxcomposite-0.4.5-h7f98852_0 None
  xorg-libxcursor    conda-forge/linux-64::xorg-libxcursor-1.2.0-h516909a_0 None
  xorg-libxdamage    conda-forge/linux-64::xorg-libxdamage-1.1.5-h7f98852_0 None
  xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.3-h7f98852_0 None
  xorg-libxext       conda-forge/linux-64::xorg-libxext-1.3.4-h516909a_0 None
  xorg-libxfixes     conda-forge/linux-64::xorg-libxfixes-5.0.3-h516909a_1004 None
  xorg-libxi         conda-forge/linux-64::xorg-libxi-1.7.10-h516909a_0 None
  xorg-libxinerama   conda-forge/linux-64::xorg-libxinerama-1.1.4-h9c3ff4c_1001 None
  xorg-libxmu        conda-forge/linux-64::xorg-libxmu-1.1.3-h516909a_0 None
  xorg-libxpm        conda-forge/linux-64::xorg-libxpm-3.5.13-h516909a_0 None
  xorg-libxrandr     conda-forge/linux-64::xorg-libxrandr-1.5.2-h516909a_1 None
  xorg-libxrender    conda-forge/linux-64::xorg-libxrender-0.9.10-h516909a_1002 None
  xorg-libxt         conda-forge/linux-64::xorg-libxt-1.1.5-h516909a_1003 None
  xorg-libxtst       conda-forge/linux-64::xorg-libxtst-1.2.3-h516909a_1002 None
  xorg-randrproto    conda-forge/linux-64::xorg-randrproto-1.5.0-h7f98852_1001 None
  xorg-recordproto   conda-forge/linux-64::xorg-recordproto-1.14.2-h7f98852_1002 None
  xorg-renderproto   conda-forge/linux-64::xorg-renderproto-0.11.1-h7f98852_1002 None
  xorg-util-macros   conda-forge/linux-64::xorg-util-macros-1.19.3-h7f98852_0 None
  xorg-xextproto     conda-forge/linux-64::xorg-xextproto-7.3.0-h7f98852_1002 None
  xorg-xproto        conda-forge/linux-64::xorg-xproto-7.0.31-h7f98852_1007 None
  xz                 conda-forge/linux-64::xz-5.2.6-h166bdaf_0 None
  zlib               conda-forge/linux-64::zlib-1.2.12-h166bdaf_4 None
  zstandard          conda-forge/linux-64::zstandard-0.18.0-py310h5764c6d_0 None
  zstd               conda-forge/linux-64::zstd-1.5.2-h6239696_4 None

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: failed

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'libexec/gio-launch-desktop'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/as/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/bg/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/bn_IN/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/ca/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/ca@valencia/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/cs/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/da/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/de/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/en_GB/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/es/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/eu/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/fr/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/gl/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/gu/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/he/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/hi/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/hr/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/hu/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/id/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/it/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/ja/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/kn/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/ko/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/lt/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/lv/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/mr/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/or/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/pa/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/pl/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/pt/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/pt_BR/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/ro/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/ru/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

SafetyError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/sk/LC_MESSAGES/glib20.mo'
has an incorrect size.
  reported size: 127561 bytes
  actual size: 8704 bytes

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/sl/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/sr/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/sv/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/ta/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/te/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/th/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/tr/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libglib located at /rds/general/user/he11/home/anaconda3/pkgs/libglib-2.74.0-h7a41b64_0
appears to be corrupted. The path 'share/locale/uk/LC_MESSAGES/glib20.mo'
specified in the package manifest cannot be found.`

**Comment by nickjcroucher** [comment]
Hi @hmedwards - I just followed the same steps as you, also on the HPC, and it seems to work OK - might just be an issue downloading one of the packages, so worth re-trying!

**Comment by johnlees** [comment]
This is likely a conda error not a poppunk error, based on the above – you might also try redoing your conda env from scratch

**Comment by hmedwards** [comment]
Thanks for the info. I've tried multiple times and the same error so perhaps I need to reinstall conda.

**Comment by johnlees** [comment]
Assuming this is fixed, please reopen if still a poppunk problem
