### ISSUE TITLE
Can't download Enterococcus faecium databases

### ISSUE THREAD

**Issue by martinmchugh** [bacpop/PopPUNK#253]
Thanks for releasing further species databases, looking forward to making use of these! 

Unfortunately I'm getting 403: Forbidden errors for both the E. faecium databases on laptop and HPC, tried a few others at random and all start downloading no problem. Using the download links here https://www.bacpop.org/poppunk/ 

Less of an issue, the N.gonorrhoeae paper link heads to a K.pneumoniae manuscript

**Comment by johnlees** [comment]
> Unfortunately I'm getting 403: Forbidden errors for both the E. faecium databases on laptop and HPC, tried a few others at random and all start downloading no problem. Using the download links here https://www.bacpop.org/poppunk/

Sorry about this! There was a permissions issue on a few of the files which should now be fixed

> Less of an issue, the N.gonorrhoeae paper link heads to a K.pneumoniae manuscript

Thanks for this too, that was a typo on my part in the table, which I'll fix when I add the final tranche

**Comment by martinmchugh** [comment]
Thanks, the Efm database downloads are working now
