### ISSUE TITLE
Wrong DB for E. coli

### ISSUE THREAD

**Issue by jpaganini** [bacpop/PopPUNK#254]
Hi guys,

I think that the link for the E. coli DB (Reference only, v2) in https://www.bacpop.org/poppunk/ is actually downloading the E. faecium DB. At least all the file names being with E_faecium*

Cheers,

**Comment by johnlees** [comment]
Apologies, that was a typo. Should now be fixed
You can also see the DBs directly here: https://ftp.ebi.ac.uk/pub/databases/pp_dbs/

**Comment by jpaganini** [comment]
Thank was quick! Thanks!
