### ISSUE TITLE
Unmatched parentheses in newick tree

### ISSUE THREAD

**Issue by drhoads** [bacpop/PopPUNK#260]
**Versions**

version 2.6.0 running in WSL2 Ubuntu (with backend: sketchlib v2.1.0
**Command used and output returned**

poppunk --create-db --output PoppunkDB --r-files r-list.txt --external-clustering external_clusters.csv --overwrite --threads 8 
poppunk --fit-model lineage --ref-db PoppunkDB --output PopPunkLineageModel --graph-weights --overwrite  --threads 8 
poppunk_visualise --ref-db PoppunkDB --model-dir PopPunkLineageModel --output Poppunk_viz --overwrite --microreact  --threads 8

**Describe the bug**

Running on 1500+ C. jejuni genomes from NCBI  Here is output from the visualize:
**********************************************
Graph-tools OpenMP parallelisation enabled: with 8 threads
PopPUNK: visualise
Loading lineage cluster model
Completed model loading
Building phylogeny
Traceback (most recent call last):
  File "/home/drhoads/miniconda3/envs/Poppunk/bin/poppunk_visualise", line 11, in <module>
    sys.exit(main())
  File "/home/drhoads/miniconda3/envs/Poppunk/lib/python3.10/site-packages/PopPUNK/visualise.py", line 624, in main
    generate_visualisations(args.query_db,
  File "/home/drhoads/miniconda3/envs/Poppunk/lib/python3.10/site-packages/PopPUNK/visualise.py", line 529, in generate_visualisations
    nj_tree = generate_nj_tree(core_distMat,
  File "/home/drhoads/miniconda3/envs/Poppunk/lib/python3.10/site-packages/PopPUNK/trees.py", line 180, in generate_nj_tree
    tree = buildRapidNJ(rapidnj, seqLabels, coreMat, outPrefix, threads = threads)
  File "/home/drhoads/miniconda3/envs/Poppunk/lib/python3.10/site-packages/PopPUNK/trees.py", line 84, in buildRapidNJ
    tree = Phylo.read(tree_filename, "newick")
  File "/home/drhoads/miniconda3/envs/Poppunk/lib/python3.10/site-packages/Bio/Phylo/_io.py", line 60, in read
    tree = next(tree_gen)
  File "/home/drhoads/miniconda3/envs/Poppunk/lib/python3.10/site-packages/Bio/Phylo/_io.py", line 49, in parse
    yield from getattr(supported_formats[format], "parse")(fp, **kwargs)
  File "/home/drhoads/miniconda3/envs/Poppunk/lib/python3.10/site-packages/Bio/Phylo/NewickIO.py", line 125, in parse
    yield self._parse_tree(buf)
  File "/home/drhoads/miniconda3/envs/Poppunk/lib/python3.10/site-packages/Bio/Phylo/NewickIO.py", line 202, in _parse_tree
    raise NewickError(
Bio.Phylo.NewickIO.NewickError: Mismatch, 983 open vs 935 close parentheses.
******************************************
Never had this happen before and not certain what to do

**Comment by johnlees** [comment]
Some questions:
- Do you have any special characters in your sample names, particularly any of `(),:;`?
- Are there any temporary files left over? It looks like it might have fallen down on the rooting step? Is there anything relevant in your output folder?
- Have you tried running without rapidnj? If you add `--rapidnj` to your command line this will use dendropy instead (though this might be slow)

**Comment by drhoads** [comment]
I had already removed all the offending characters including slash (/) and space.
There were files written to the Poppunk_viz folder including a clusters.csv and NJ.nwk tree, but microreact gave me a spinning circle when I tried to load the .nwk tree file.
When I looked at the help for poppunk_visualise it says that to use --rapidnj I need to provide the path to the rapidnj binary and I am not certain where to look for that.  I did see that I could use the --tree mst, which did complete with out errors, and then if I tried --tree nj it gave the same crash with unmatched parentheses.  I see there are additional options for --tree mst using the --mst-distances where I can specify core/accessory and I assume Euclidean is "both"??  That seems to be what it says in the documentation: "Note The default in this mode is to use core distances, but you can use accessory or Euclidean core-accessory ..."

I ran the poppunk_visualise using --tree mst with the default --mst-distances core and euclidean and both completed so I am not certain why the --tree nj is crashing.

**Comment by drhoads** [comment]
Not that it is your concern but there now seems to be a problem loading the output into MicroReact, if I edit the .csv file to add metadata.  So I tried Phandango which does not like the .nwk tree because it is prefaced with a [&R] which I do not understand as I am not fluent in Newick but do understand at least some of the structure.  I did not find anything in some simple Google searches or at https://evolution.genetics.washington.edu/phylip/newicktree.html

**Comment by nickjcroucher** [comment]
- Is the tree you generated an NJ tree built with native python, an NJ tree built with rapidnj, or an MST?
- What happens if you specify the full set of distances in the original database with `--distances` when building the tree?

**Comment by johnlees** [comment]
The `[&R]` forces rooting the tree, but isn't support by all newick readers

> When I looked at the help for poppunk_visualise it says that to use --rapidnj I need to provide the path to the rapidnj binary and I am not certain where to look for that.

Sorry if this is unclear, if you simply add `--rapidnj` without any argument (i.e. just as a flag) it will be 'blank' and then not use it.

> There were files written to the Poppunk_viz folder including a clusters.csv and NJ.nwk tree, but microreact gave me a spinning circle when I tried to load the .nwk tree file.

Could you post your NJ.nwk tree here?

**Comment by drhoads** [comment]
Unfortunately the program says you have to provide an argument
(Poppunk) drhoads@ARSC-A-G4LJXP3:/mnt/f/DNAwork/cjejuni$ poppunk_visualise --ref-db PoppunkDB --model-dir PopPunkLineageModel --output Poppunk_viz --rapidnj --tree nj --overwrite --microreact  --threads 8
usage: poppunk_visualise [-h] --ref-db REF_DB [--query-db QUERY_DB] [--distances DISTANCES] [--rank-fit RANK_FIT]
                         [--include-files INCLUDE_FILES] [--external-clustering EXTERNAL_CLUSTERING]
                         [--model-dir MODEL_DIR] [--previous-clustering PREVIOUS_CLUSTERING]
                         [--previous-query-clustering PREVIOUS_QUERY_CLUSTERING] [--previous-mst PREVIOUS_MST]
                         [--previous-distances PREVIOUS_DISTANCES] [--network-file NETWORK_FILE]
                         [--display-cluster DISPLAY_CLUSTER] --output OUTPUT [--overwrite] [--core-only]
                         [--accessory-only] [--microreact] [--cytoscape] [--phandango] [--grapetree]
                         [--tree {nj,mst,both,none}] [--mst-distances {core,accessory,euclidean}] [--rapidnj RAPIDNJ]
                         [--api-key API_KEY] [--perplexity PERPLEXITY] [--info-csv INFO_CSV] [--threads THREADS]
                         [--gpu-dist] [--gpu-graph] [--deviceid DEVICEID] [--strand-preserved] [--version]
poppunk_visualise: error: argument --rapidnj: expected one argument
(Poppunk) drhoads@ARSC-A-G4LJXP3:/mnt/f/DNAwork/cjejuni$

This is the output without the --rapidnj :
(Poppunk) drhoads@ARSC-A-G4LJXP3:/mnt/f/DNAwork/cjejuni$ poppunk_visualise --ref-db PoppunkDB --model-dir PopPunkLineageModel --output Poppunk_viz --tree nj --overwrite --microreact  --threads 8

Graph-tools OpenMP parallelisation enabled: with 8 threads
PopPUNK: visualise
Loading lineage cluster model
Completed model loading
Building phylogeny
Traceback (most recent call last):
  File "/home/drhoads/miniconda3/envs/Poppunk/bin/poppunk_visualise", line 11, in <module>
    sys.exit(main())
  File "/home/drhoads/miniconda3/envs/Poppunk/lib/python3.10/site-packages/PopPUNK/visualise.py", line 624, in main
    generate_visualisations(args.query_db,
  File "/home/drhoads/miniconda3/envs/Poppunk/lib/python3.10/site-packages/PopPUNK/visualise.py", line 529, in generate_visualisations
    nj_tree = generate_nj_tree(core_distMat,
  File "/home/drhoads/miniconda3/envs/Poppunk/lib/python3.10/site-packages/PopPUNK/trees.py", line 180, in generate_nj_tree
    tree = buildRapidNJ(rapidnj, seqLabels, coreMat, outPrefix, threads = threads)
  File "/home/drhoads/miniconda3/envs/Poppunk/lib/python3.10/site-packages/PopPUNK/trees.py", line 84, in buildRapidNJ
    tree = Phylo.read(tree_filename, "newick")
  File "/home/drhoads/miniconda3/envs/Poppunk/lib/python3.10/site-packages/Bio/Phylo/_io.py", line 60, in read
    tree = next(tree_gen)
  File "/home/drhoads/miniconda3/envs/Poppunk/lib/python3.10/site-packages/Bio/Phylo/_io.py", line 49, in parse
    yield from getattr(supported_formats[format], "parse")(fp, **kwargs)
  File "/home/drhoads/miniconda3/envs/Poppunk/lib/python3.10/site-packages/Bio/Phylo/NewickIO.py", line 125, in parse
    yield self._parse_tree(buf)
  File "/home/drhoads/miniconda3/envs/Poppunk/lib/python3.10/site-packages/Bio/Phylo/NewickIO.py", line 202, in _parse_tree
    raise NewickError(
Bio.Phylo.NewickIO.NewickError: Mismatch, 983 open vs 935 close parentheses.
I added the extension .txt and attached the Newick file.  Hope this helps

[Poppunk_viz_core_NJ.nwk.txt](https://github.com/bacpop/PopPUNK/files/11157806/Poppunk_viz_core_NJ.nwk.txt)

**Comment by johnlees** [comment]
I am seeing the same error loading this file into R. I still suspect it's most likely a problem with a sample name. Do you have any names which have a bracket in, or any names which are just a number (so not a string)? Could you post a list of your sample names here (ideally your `r-list.txt`)

**Comment by drhoads** [comment]
This is the r-list file.  I do have some numbers but have had numbers in previous data sets.
[r-list.txt](https://github.com/bacpop/PopPUNK/files/11226227/r-list.txt)

**Comment by johnlees** [comment]
One I can spot that looks like it might cause a problem in a newick file: `81116;_NCTC_11828`

**Comment by drhoads** [comment]
SUCCESS!  I have added semicolon (and colon) to my documentation on cleaning up strain names for phylogenomics (along with space comma period bracket parentheses).  I was able to get a NJ tree that directly addresses what I was trying to visualize.   Thank you very much for your help, and for a great program.  I have been using poppunk for many years on many different species.

 BTW- is there any followup on my comment that I was unable to add --rapidnj to the command because I got an error saying that I needed to provide an argument for that option (see bold).

Poppunk) drhoads@ARSC-A-G4LJXP3:/mnt/f/DNAwork/cjejuni$ poppunk_visualise --ref-db PoppunkDB --model-dir PopPunkLineageModel --output Poppunk_viz --rapidnj --tree nj --overwrite --microreact --threads 8
usage: poppunk_visualise [-h] --ref-db REF_DB [--query-db QUERY_DB] [--distances DISTANCES] [--rank-fit RANK_FIT]
[--include-files INCLUDE_FILES] [--external-clustering EXTERNAL_CLUSTERING]
[--model-dir MODEL_DIR] [--previous-clustering PREVIOUS_CLUSTERING]
[--previous-query-clustering PREVIOUS_QUERY_CLUSTERING] [--previous-mst PREVIOUS_MST]
[--previous-distances PREVIOUS_DISTANCES] [--network-file NETWORK_FILE]
[--display-cluster DISPLAY_CLUSTER] --output OUTPUT [--overwrite] [--core-only]
[--accessory-only] [--microreact] [--cytoscape] [--phandango] [--grapetree]
[--tree {nj,mst,both,none}] [--mst-distances {core,accessory,euclidean}] [--rapidnj RAPIDNJ]
[--api-key API_KEY] [--perplexity PERPLEXITY] [--info-csv INFO_CSV] [--threads THREADS]
[--gpu-dist] [--gpu-graph] [--deviceid DEVICEID] [--strand-preserved] [--version]
**poppunk_visualise: error: argument --rapidnj: expected one argument**
