### ISSUE TITLE
--write-references option when running PopPUNK assign

### ISSUE THREAD

**Issue by avrilcoghlan** [bacpop/PopPUNK#265]
Hello,

I am using poppunk 2.6.0 on the Sanger farm.  

I built a database for Vibrio cholerae using poppunk and now tried assigning some other sequences, using the command:

poppunk_assign --db chun_poppunk_db1 --model-dir chun_poppunk_db_fitted1 --query vibriowatch_fastas/input_file --output test_assign_vibriowatch_poppunk_clusters --serial --write-references

Some of the new sequences that I assigned were in already used to make the initial database, which is why I used the '--write-references' option. 
I found that in the output csv file of poppunk clusters, some of these were identified with '_query' added to the sequence name.
However, there were other sequences that I knew were used to make the initial database, but they didn't have '_query' added to the sequence name in the output csv file, even though I would have expected them to be.
I'm wondering is that a bug? 

Regards,
Avril

**Comment by johnlees** [comment]
So to summarise, you've got some queries in the initial database, not identified as queries in the final output?

Can you check in your original fit `chun_poppunk_db_fitted1` that:
- They definitely have identical names.
- Whether they appear in the 'references' files

**Comment by johnlees** [comment]
Closing due to lack of response
