### ISSUE TITLE
[database] A double-checked database of Neisseria meningitidis

### ISSUE THREAD

**Issue by tanzhizhou** [bacpop/PopPUNK#267]
Hi johnlees,

Please specify:
- Is this a request for us to make a new database?
No

- Is this a database you have fitted, and wish us to add?
Yes

If the latter:
- What is the species?
 Neisseria meningitidis

- How many genomes are included?
 26801

- Are the genomes public?
Yes, All genomes were downloaded from PubMLST website.

- Are the genomes published?
Yes

- How did you obtain your fit?
the database was fitted to the dbscan model

**I know that there is a database of Neisseria meningitidis already in your website, however, I found that the genome quality of Neisseria meningitidis in PubMLST is not good enough, and some isolates were even not belong to the species of Neisseria meningitidis.**

For that reason, in this version of database, all the genomes of isolates were validated by species identification function (taxonomy_wf) in Genome Database Taxonomy toolkit (GTDB-Tk). Quality of the genomes were assessed using CheckM software. Of the isolates, only those with a completeness rate of ≥90% and a contamination rate of ≤5% were considered suitable for Poppunk model fitting and clustering. 

Could I submit this database to your website?

Zhizhou Tan

Chinese CDC

**Comment by johnlees** [comment]
Thanks for this contribution, we would be very happy to make this the updated version on the website as it sounds like you've done a much more thorough QC of the data. I might suggest that we use your sketches with the existing model fit, to maintain as much backwards compatibility as possible.

It may be convenient to upload your data here: https://imperialcollegelondon.app.box.com/f/3c4781a2f5ad4215b12a62099ed5cc63
Then I can run through with the previous model and update the website.

Please also let me know if you have any preferred citation or attribtion for this that you'd like me to include on the page.

**Comment by tanzhizhou** [comment]
> Thanks for this contribution, we would be very happy to make this the updated version on the website as it sounds like you've done a much more thorough QC of the data. I might suggest that we use your sketches with the existing model fit, to maintain as much backwards compatibility as possible.
> 
> It may be convenient to upload your data here: https://imperialcollegelondon.app.box.com/f/3c4781a2f5ad4215b12a62099ed5cc63 Then I can run through with the previous model and update the website.
> 
> Please also let me know if you have any preferred citation or attribtion for this that you'd like me to include on the page.

Hi John,

Many thanks for you detailed suggestion. I am really sorry for the late reply because our project have been delay for several months. Could I still upload the our database to your website?

https://imperialcollegelondon.app.box.com/f/3c4781a2f5ad4215b12a62099ed5cc63

The Neisseria_meningitidis database is 24GB in size, I think I can complete the submission this week

**Comment by tanzhizhou** [comment]
Hi John,

I have complete the submission of Neisseria meningitidis database, named as Neisseria_meningitidis_26801_refs.tar.bz2 to your link https://imperialcollegelondon.app.box.com/f/3c4781a2f5ad4215b12a62099ed5cc63

What should I do next?

All the best,
Zhizhou
China CDC

**Comment by tanzhizhou** [comment]
Hi John,

Many thanks for your email and help!

It is great news that this database is available on your website. The paper
that describes this database is still under review. We will still need your
help to update the information of this database on the website once the
paper has been published.

Thanks again for your help!

All the best,
Zhizhou

John Lees ***@***.***> 于2024年2月27日周二 01:13写道：

**Comment by johnlees** [comment]
Great, do let us know when your paper has been published and we'll be happy to update the reference
