### ISSUE TITLE
PackagesNotFoundError

### ISSUE THREAD

**Issue by RoyUnderwoodAbramski** [bacpop/PopPUNK#283]
**Versions** Not able to install a version of PoPPUNK  Receive Error:  _**PackagesNotFoundError**_

I ran the following commands on Ubuntu 20.04
` conda install poppunk`

**Here is the Output**
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - poppunk

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

Please Advise

**Comment by johnlees** [comment]
You'll need to add the bioconda and conda-forge channels first, as described here:
https://poppunk.readthedocs.io/en/latest/installation.html#installing-with-conda-recommended

**Comment by RoyUnderwoodAbramski** [comment]
I had all 3 listed.  
I resolved the issue, thank you for your hep Johnlees
