### ISSUE TITLE
issues with assigning GPSCs

### ISSUE THREAD

**Issue by johnlees** [bacpop/PopPUNK#311]
I am also having issues with assigning GPSCs -- the external clustering file labels every strain as "NA" even though the GPSC of most of these strains have been previously established. My cytoscape network also produces a lot more distinct clusters than I'd expect given how closely related the strains are, so I wonder if these issues are related at all to the previous one.

_Originally posted by @sydelstan in https://github.com/bacpop/PopPUNK/issues/309#issuecomment-2111339654_

**Comment by johnlees** [comment]
@sydelstan opening new issue to track this

I'd require more information to diagnose this: command and ideally a minimal reproducible example (e.g. a genome that causes this issue)

**Comment by sydelstan** [comment]
Hello,

I used the code 

poppunk_assign --db GPS_v8_ref --external-clustering GPS_v8_external_clusters.csv --query qfile.txt --output <output folder>

based on these instructions: 

https://www.pneumogen.net/gps/#/training

These are some of the accession numbers I used:

ERR884352
ERR884330
ERR1788221
ERR025290
SRR3661255
ERR884389

**Comment by johnlees** [comment]
I have checked with my colleague @HarryHung in the GPS project who says the following:

> Checking ERR884352
> It is one of the GPS samples with:
> Public Name: GPS_PL_1533_10
> This sample has been re-analysed by the GPS Pipeline just few days ago, and its GPSC is correctly assigned to GPSC 12 with v8_ref database and PopPUNK v2.6.3 (via Docker image staphb/poppunk:2.6.3)
 
> I am not sure what is going on their side. I wonder if they are using raw reads as input (in my pipeline, pre-processing and de novo assembly were done before passing the assemblies to PopPUNK)? Or it could be some installation issues (might try out the Docker image)?

Are you using reads or an assembly as input?

**Comment by sydelstan** [comment]
I used raw reads, I will switch to assemblies, thanks
