### ISSUE TITLE
xxx.dists.npy is required in poppunk_visualize but not available in v2.7.0

### ISSUE THREAD

**Issue by Jamesped** [bacpop/PopPUNK#330]
**Versions**
2.7.0

**Command used and output returned**
poppunk_visualise --ref-db ./poppunk_cluster_4th --output Kp_viz --microreact

**Describe the bug**
FileNotFoundError: [Errno 2] No such file or directory: './poppunk_cluster_4th/poppunk_cluster_4th.dists.npy'

The same error appears in other visualize tool such as Cytoscape.

**Comment by johnlees** [comment]
This might have been caused by #320 which removed .npy files from assignment, but I don't think it should break the use like this. What are the commands you used to generate the `--ref-db`, and what does the `poppunk_cluster_4th` directory contain?

Also in the error, can you post the full traceback with the line which is throwing?

**Comment by Jamesped** [comment]
I am working on 294 K. pneumoniae strains and use the PopPUNK provided database (https://ftp.ebi.ac.uk/pub/databases/pp_dbs/Klebsiella_pneumoniae_v3_full.tar.bz2)

After the command ` poppunk_assign --db /media/psf/tb8owc/ref_genome/Poppunk/Klebsiella_pneumoniae_v3_full --query qfile --output poppunk_cluster_4th --update-db`, it appeared to be successful with the following message.

PopPUNK: assign
	(with backend: sketchlib v2.1.1
	 sketchlib: /home/parallels/miniconda3/lib/python3.9/site-packages/pp_sketchlib.cpython-39-x86_64-linux-gnu.so)
Mode: Assigning clusters of query sequences

Graph-tools OpenMP parallelisation enabled: with 1 threads
Sketching 294 genomes using 1 thread(s)
Progress (CPU): 294 / 294
Writing sketches to file
Loading previously refined model
Completed model loading
WARNING: versions of input databases sketches are different, results may not be compatible
Calculating distances using 1 thread(s)
Progress (CPU): 100.0%
Loading network from /media/psf/tb8owc/ref_genome/Poppunk/Klebsiella_pneumoniae_v3_full/Klebsiella_pneumoniae_v3_full_graph.gt
Network loaded: 1360 samples
Loading previous cluster assignments from /media/psf/tb8owc/ref_genome/Poppunk/Klebsiella_pneumoniae_v3_full/Klebsiella_pneumoniae_v3_full_clusters.csv
Calculating all query-query distances
Calculating random match chances using Monte Carlo
Calculating distances using 1 thread(s)
Progress (CPU): 100.0%
Clusters 48,128 have merged into 48_128
Clusters 39,199 have merged into 39_199
Clusters 171,266 have merged into 171_266
Updating reference database to poppunk_cluster_4th
Updating random match chances
Calculating random match chances using Monte Carlo

Done

The contains in the directory poppunk_cluser_4th are

total 242164
drwxr-xr-x 1 parallels parallels       408 Oct  2 10:44 ./
drwxr-xr-x 1 parallels parallels     10404 Oct  2 10:40 ../
-rw-rw-r-- 1 parallels parallels     26260 Oct  2 10:44 poppunk_cluster_4th_clusters.csv
-rw-rw-r-- 1 parallels parallels     24808 Oct  2 10:44 poppunk_cluster_4th.dists.pkl
-rw-rw-r-- 1 parallels parallels      1081 Oct  2 10:44 poppunk_cluster_4th_fit.npz
-rw-rw-r-- 1 parallels parallels        26 Oct  2 10:44 poppunk_cluster_4th_fit.pkl
-rw-rw-r-- 1 parallels parallels     66723 Oct  2 10:44 poppunk_cluster_4th_graph.gt
-rw-rw-r-- 1 parallels parallels 185448330 Oct  2 10:44 poppunk_cluster_4th.h5
-rw-rw-r-- 1 parallels parallels      6476 Oct  2 10:44 poppunk_cluster_4th.refs
-rw-rw-r-- 1 parallels parallels      4740 Oct  2 10:44 poppunk_cluster_4th.refs_graph.gt
-rw-rw-r-- 1 parallels parallels  62349738 Oct  2 10:44 poppunk_cluster_4th.refs.h5
-rw-rw-r-- 1 parallels parallels      2425 Oct  2 10:44 poppunk_cluster_4th_unword_clusters.csv

When I try to visualize the output with the following command `poppunk_visualise --ref-db poppunk_cluster_4th --output Kp_viz --microreact`, it shows an error message like this:

Graph-tools OpenMP parallelisation enabled: with 1 threads
PopPUNK: visualise
Traceback (most recent call last):
  File "/home/parallels/miniconda3/bin/poppunk_visualise", line 11, in <module>
    sys.exit(main())
  File "/home/parallels/miniconda3/lib/python3.9/site-packages/PopPUNK/visualise.py", line 632, in main
    generate_visualisations(args.query_db,
  File "/home/parallels/miniconda3/lib/python3.9/site-packages/PopPUNK/visualise.py", line 288, in generate_visualisations
    rlist, qlist, self, complete_distMat = readPickle(distances)
  File "/home/parallels/miniconda3/lib/python3.9/site-packages/PopPUNK/utils.py", line 193, in readPickle
    X = np.load(pklName + ".npy")
  File "/home/parallels/miniconda3/lib/python3.9/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'poppunk_cluster_4th/poppunk_cluster_4th.dists.npy'

**Comment by johnlees** [comment]
As you're doing visualisation after query assignment, you want a command of the form:
```
poppunk_visualise --ref-db example_db --query-db example_query --output example_viz --microreact
```
i.e. point --ref-db to `/media/psf/tb8owc/ref_genome/Poppunk/Klebsiella_pneumoniae_v3_full` and --query-db to `poppunk_cluster_4th`.

See this section of the docs: https://poppunk.bacpop.org/visualisation.html#common-options

**Comment by Jamesped** [comment]
Thank you, Johnlee.
It worked fine, but only when the query-db was created by `poppunk_assign` without the option `-update-db` .  The same error occurred when the `-update-db' was added during the assignment procedure.
